# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='refresh_token',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
